

POST https://app-orderhub-api-mramos-staging.azurewebsites.net/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@orderhub.com",
  "password": "Admin123*"
}  

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5Ab3JkZXJodWIuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzgxMjEyMDA5fQ.MNNDTpUlCc3YoPrkNSoj73FGjpC5lYWPHMWHKk5RIl4


### Consulta ordenes
GET https://app-orderhub-api-mramos-staging.azurewebsites.net/orders
Authorization: Bearer {{token}}



### Crear Orden
POST https://app-orderhub-api-mramos-staging.azurewebsites.net/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "customerId": "cust-008",
  "total": 120,
  "status": "Pending"
}

### Obtener una orden por id
DELETE https://app-orderhub-api-mramos-staging.azurewebsites.net/orders/6
Authorization: Bearer {{token}}
Content-Type: application/json
 